[workspace]

members = [
    "mio-and-recvmsg",
    "mio-UdpDgram",
    "mio-UnixStream",
    "mio-UnixDgram",
    "mio-UnixPipe",
    "mio-TcpStream",
    "tokio-UdpDgram",
    "multipath-Udp",
    "transfer-fd",
    "poll-read",
    "embedded-tls-efi",
]
