[package]
name = "embedded-tls-efi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ffi = { package = "efi_ffi", version = "0.1.1" }
efi = { git = "https://github.com/gurry/efi"}