[package]
name = "tokio_udp_dgram"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc  = "0.2"
tokio = { version = "1.19" , features = ["full", "tracing"] }